### ISSUE TITLE
Store the GitHub profile images

### ISSUE THREAD

**Issue by adrienpoly** [adrienpoly/rubyvideo#330]
Follow-up to #328 

up to now we rely on GitHub to serve the profile images. Very easy to use on our side but it comes with a few gotchas. 

We are dependent on GitHub availability and the cache settings cannot be configured. Since GitHub picture profile have very short live cache the images are rarely cached in the browser and can introduce a few blink effect. 

I would like to avoid setting up an S3/R2 storage (but open to change my mind)

my idea would be to use the 40gb storage available on the VPs with an active storage configured using the file system. 

for the picture profile we could check if one is attached if not fallback to GitHub and launch a background job to attach the image and persist it locally. This way in dev we don’t have to worry about pulling the data and the storage gets constructed slowly overtime

happy to hear alternative suggestions

**Comment by marcoroth** [comment]
One other thing I was wondering, we are referencing the GitHub avatars using an URL that redirects (`github.com/[handle].png`). I wonder if it's more reliable if we use the URL version where it doesn't have to redirect to get the image (`avatars.githubusercontent.com/u/[user_is]`) because it presuable doesn't have to go through their app and can just hit the CDN.
